// AUTO-GENERATED by scripts/generate-map.mjs — do not edit by hand.
export const MAP_VIEWBOX = { width: 98, height: 58 } as const;

/** Dots live in /public/map-dots.svg (same viewBox). */
export const MAP_DOTS_SRC = "/map-dots.svg";

export const MAP_CITIES = {
  "belgrade": {
    "x": 25,
    "y": 14.72
  },
  "kathmandu": {
    "x": 70.5,
    "y": 29.44
  },
  "jakarta": {
    "x": 85.5,
    "y": 53.69
  },
  "tashkent": {
    "x": 59,
    "y": 18.19
  },
  "nairobi": {
    "x": 36.5,
    "y": 50.23
  },
  "dubai": {
    "x": 49.5,
    "y": 31.18
  },
  "newDelhi": {
    "x": 65,
    "y": 28.58
  }
} as const;

export type CityKey = keyof typeof MAP_CITIES;
