/**
 * Generates lib/map-data.ts from the `dotted-map` package.
 * Run with: npm run generate:map
 * Output: one compact SVG path for all dots + projected city coordinates.
 */
import fs from "node:fs";
import path from "node:path";
import DottedMap from "dotted-map";

const CITIES = {
  belgrade: { lat: 44.79, lng: 20.45 },
  kathmandu: { lat: 27.72, lng: 85.32 },
  jakarta: { lat: -6.21, lng: 106.85 },
  tashkent: { lat: 41.3, lng: 69.24 },
  nairobi: { lat: -1.29, lng: 36.82 },
  dubai: { lat: 25.2, lng: 55.27 },
  newDelhi: { lat: 28.61, lng: 77.21 },
};

// Europe, Africa, Middle East, South & Southeast Asia.
const map = new DottedMap({
  height: 58,
  grid: "diagonal",
  region: { lat: { min: -12, max: 58 }, lng: { min: -15, max: 125 } },
});

const round = (n) => Math.round(n * 100) / 100;

// Every dot is a zero-length subpath ("M x y h0"). Rendered with
// stroke-linecap="round", each becomes a circle — one DOM node, tiny payload.
const d = map
  .getPoints()
  .map(({ x, y }) => `M${round(x)} ${round(y)}h0`)
  .join("");

const cities = Object.fromEntries(
  Object.entries(CITIES).map(([key, coords]) => {
    const p = map.getPin(coords);
    return [key, { x: round(p.x), y: round(p.y) }];
  }),
);

const { width, height } = map.image;
const out = `// AUTO-GENERATED by scripts/generate-map.mjs — do not edit by hand.
export const MAP_VIEWBOX = { width: ${round(width)}, height: ${round(height)} } as const;

/** Dots live in /public/map-dots.svg (same viewBox). */
export const MAP_DOTS_SRC = "/map-dots.svg";

export const MAP_CITIES = ${JSON.stringify(cities, null, 2)} as const;

export type CityKey = keyof typeof MAP_CITIES;
`;

// Dots as a static, cacheable SVG (kept out of the JS bundle and the HTML).
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${round(width)} ${round(height)}"><path d="${d}" fill="none" stroke="#B9ACA2" stroke-width="0.42" stroke-linecap="round"/></svg>`;
fs.writeFileSync(path.resolve(import.meta.dirname, "../public/map-dots.svg"), svg);

const target = path.resolve(import.meta.dirname, "../lib/map-data.ts");
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, out);
console.log(`map-data.ts written: ${map.getPoints().length} dots, ${width}x${height}`, cities);
